# Generated by Django 2.2.5 on 2020-01-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0004_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingparameter',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
