# Generated by Django 2.2.5 on 2020-01-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0005_bookingparameter_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='failure_reason',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
