# Generated by Django 2.2.5 on 2020-01-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0006_auto_20200105_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='court_number',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
