# Generated by Django 2.2.5 on 2020-01-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0009_auto_20200106_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_screenshot',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
